// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSHpnOYTcmL8mNNOswoVYN9UAgCl2JY_E',
    appId: '1:682036958779:web:74fffa51b02402ba402e1e',
    messagingSenderId: '682036958779',
    projectId: 'snaplearn-db6d0',
    authDomain: 'snaplearn-db6d0.firebaseapp.com',
    storageBucket: 'snaplearn-db6d0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLoMHROpIBggVT3xGWpsdeGNVOd3Fvx3A',
    appId: '1:682036958779:android:e3a5ceb75a4971e7402e1e',
    messagingSenderId: '682036958779',
    projectId: 'snaplearn-db6d0',
    storageBucket: 'snaplearn-db6d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMNO7gdt8rM5YROVAQf1UV5lY2gTIO3wI',
    appId: '1:682036958779:ios:816002436ac58511402e1e',
    messagingSenderId: '682036958779',
    projectId: 'snaplearn-db6d0',
    storageBucket: 'snaplearn-db6d0.appspot.com',
    iosBundleId: 'com.example.snaplearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMNO7gdt8rM5YROVAQf1UV5lY2gTIO3wI',
    appId: '1:682036958779:ios:25030071957cdf78402e1e',
    messagingSenderId: '682036958779',
    projectId: 'snaplearn-db6d0',
    storageBucket: 'snaplearn-db6d0.appspot.com',
    iosBundleId: 'com.example.snaplearn.RunnerTests',
  );
}
